apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: flask-demo:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root-password

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
